services:
  - type: web
    name: gtscanvas-backend
    env: python
    python_version: 3.12.2
    build_command: pip install --upgrade pip && pip install -r requirements.txt
    start_command: uvicorn main:app --host 0.0.0.0 --port $PORT
